### ISSUE TITLE
Errors in creating batches of prefab models

### ISSUE THREAD

**Issue by yamins81** [dicarlolab/ThreeDWorld#15]
@sharatb 

The is that arose the other day in converting batches if 3d models to prefabs is ending up being pretty problematic.    Basically, the phenomenon that occurs is something like
    1) I'll click on a folder of models to convert, and run the creation function from the tab. 
    2) The system will convert about 10 models or so fine
    3) Then it slows dow and stops converting.  Eventually some kind of error message is thrown, sometimes about a "mesh is referenced but no longer exists", and sometimes something else.  
    4) Unity freezes. 
    5) when I restart unity, none of the meshes that previously appear to have been converted have anything saved -- or sometimes, there's some prefab saved, but it's not complete (e.g. has only a one or two of the collision meshes included)

We suspected that this was a memory problem at first, but I ran this on a machine with > 12GB, and monitored memory usage the whole time.  I observed the problem even though the system had not run out of memory.   I tried this on two different OSX machines and observed the same problem.   When looking in the unity editor log I unfortunately don't see anything that looks related to the problem.   

So, @sharatb, can you see if this problem is happening on your machine?   That is, import a whole directory of models from the /home/yamins/test_vhacd directory and then run the prefab creation function on that directory.  Can you recreate the problem?    Or is it specific to OSX?

**Comment by pbashivan** [comment]
Ultimate Game Tools Library had a method called readVRML which would read the wrl file and extract meshes from it, however, a line of code had a condition which checked the number of triangles per c.hull, and would not let this number exceed 255. However the attribute used for checking this actually gave 3 times the number of triangles in the hull, thus excluding some legal triangles. Further vhacd has a tag: maxNumVerticesPerCH which was set to 255. We have decided that that minimum number of vertices it would take to form a mesh of 254 triangles would be 129 vertices. The mesh that would form this would be two n-sided pyramids sandwiched together at the bases. If you can think of a case that uses fewer vertices, let us know.
