### ISSUE TITLE
Stabilize Prefab Generation

### ISSUE THREAD

**Issue by jazzguitarist** [dicarlolab/ThreeDWorld#40]
Look into various ways to make the prefab generation work or at least persist when it fails to generate the prefab of an object.

**Comment by yamins81** [comment]
see this

[(http://answers.unity3d.com/questions/425199/how-do-i-release-editor-memory.html)]

**Comment by yamins81** [comment]
but also this

http://forum.unity3d.com/threads/running-out-of-memory-building-a-bunch-of-asset-bundles-in-the-editor.196529/

see the comment at the end about SaveAssets

**Comment by yamins81** [comment]
resolved at least for now by running editor in Play mode
