### ISSUE TITLE
Find and return object centroids in scene info

### ISSUE THREAD

**Issue by jazzguitarist** [dicarlolab/ThreeDWorld#52]

**Comment by yamins81** [comment]
you could return either "room space" or in "camera view space" or both

**Comment by yamins81** [comment]
find = compute this using simple unity functions
return = put this in the json so that agents / dataset creation can use it

**Comment by yamins81** [comment]
And this should also include the poses of objects.  And the avatar should be included in the list of objects about which one gets info.

**Comment by damro** [comment]
This is done. Look at documentation of how to get the information.
