### ISSUE TITLE
cache model data so models don't need to be loaded on start up

### ISSUE THREAD

**Issue by yamins81** [dicarlolab/ThreeDWorld#68]
Whatever data is needed to filter models for use with procedural generation should be cached.   Options include:

1) put the data into the mongodb and that access the mongodb from Unity
2) use a unity-local database (like used to be used for prefabdatabase
3) put stuff in a json document that's loaded and saved.

**Comment by yamins81** [comment]
This is very time sensitive.

**Comment by pbashivan** [comment]
Is this going to fix the long loading time when starting a new simulation?
Everytime I'm starting a new unity simulation (through the tdw_queue) it takes a long time to start up. Does this thread affect this issue?

**Comment by chengxuz** [comment]
Done. See instructions of "Mongodb Integration" in README
