### ISSUE TITLE
Scene switch does not return sceneInfo anymore

### ISSUE THREAD

**Issue by pbashivan** [dicarlolab/ThreeDWorld#71]
Working on the new build from asset bundles (500 bundles). When I try the scene switch
`
       sock.send_json({'n': 4, 'msg': {"msg_type": "SCENE_SWITCH",
                                             "config": config,
                                             'sendSceneInfo': True,
                                             }})
`
The message returned does not contain `sceneInfo`
The same operation using previous stable build "05" would return it.

@chengxuz Any thoughts?

**Comment by qbilius** [comment]
I changed it to send_scene_info a long time ago, try that.

**Comment by pbashivan** [comment]
That was indeed the issue. 
Thanks
