### ISSUE TITLE
Deal with various memory leaks

### ISSUE THREAD

**Issue by yamins81** [dicarlolab/ThreeDWorld#74]
1. Garbage collection: Remove garbage collection from the update loop of the prefab database function and put it somewhere so it only gets called rarely.  but  do it sometimes!

2. see if there is a memory leak when switchings scene and if so, fix it.

**Comment by yamins81** [comment]
If it's not obvious where th leaks are coming from we can tolerate the "kill the process solution"

**Comment by damro** [comment]
did the garbage collection, memory leaks don't seem to appear afterwards
