### ISSUE TITLE
Some of the generated assetbundles don't have textures on them

### ISSUE THREAD

**Issue by chengxuz** [dicarlolab/ThreeDWorld#76]
The color of their mesh is just (255,255,255,255) for RGBA. Problems of material processing or flags of textures?

**Comment by chengxuz** [comment]
Seems to be the problem of flags?

**Comment by qbilius** [comment]
Should be fixed now. The order of texture assignment in shapenet.py in dldata was not controlled.

Can't push the updated code until dldata's PR is merged.
